[tool.commitizen]
version = "1.0.16"
version_files = [
    "node/package.json",
    "node-ts/package.json",
    "electron/package.json",
    "python/pyproject.toml",
    "python/mscompress/__init__.py:__version__",
]
create_tag = false
