# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cgrams/mscompress_dev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cgrams/mscompress_dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cgrams/mscompress_dev/CMakeFiles /home/cgrams/mscompress_dev//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cgrams/mscompress_dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mscompress

# Build rule for target.
mscompress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mscompress
.PHONY : mscompress

# fast build rule for target.
mscompress/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/build
.PHONY : mscompress/fast

#=============================================================================
# Target rules for targets named zlib_build

# Build rule for target.
zlib_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_build
.PHONY : zlib_build

# fast build rule for target.
zlib_build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zlib_build.dir/build.make CMakeFiles/zlib_build.dir/build
.PHONY : zlib_build/fast

#=============================================================================
# Target rules for targets named zstd

# Build rule for target.
zstd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd
.PHONY : zstd

# fast build rule for target.
zstd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/build
.PHONY : zstd/fast

#=============================================================================
# Target rules for targets named yxml

# Build rule for target.
yxml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yxml
.PHONY : yxml

# fast build rule for target.
yxml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yxml.dir/build.make CMakeFiles/yxml.dir/build
.PHONY : yxml/fast

#=============================================================================
# Target rules for targets named base64

# Build rule for target.
base64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 base64
.PHONY : base64

# fast build rule for target.
base64/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/build
.PHONY : base64/fast

src/algo.o: src/algo.c.o
.PHONY : src/algo.o

# target to build an object file
src/algo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/algo.c.o
.PHONY : src/algo.c.o

src/algo.i: src/algo.c.i
.PHONY : src/algo.i

# target to preprocess a source file
src/algo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/algo.c.i
.PHONY : src/algo.c.i

src/algo.s: src/algo.c.s
.PHONY : src/algo.s

# target to generate assembly for a file
src/algo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/algo.c.s
.PHONY : src/algo.c.s

src/compress.o: src/compress.c.o
.PHONY : src/compress.o

# target to build an object file
src/compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/compress.c.o
.PHONY : src/compress.c.o

src/compress.i: src/compress.c.i
.PHONY : src/compress.i

# target to preprocess a source file
src/compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/compress.c.i
.PHONY : src/compress.c.i

src/compress.s: src/compress.c.s
.PHONY : src/compress.s

# target to generate assembly for a file
src/compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/compress.c.s
.PHONY : src/compress.c.s

src/debug.o: src/debug.c.o
.PHONY : src/debug.o

# target to build an object file
src/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/debug.c.o
.PHONY : src/debug.c.o

src/debug.i: src/debug.c.i
.PHONY : src/debug.i

# target to preprocess a source file
src/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/debug.c.i
.PHONY : src/debug.c.i

src/debug.s: src/debug.c.s
.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/debug.c.s
.PHONY : src/debug.c.s

src/decode.o: src/decode.c.o
.PHONY : src/decode.o

# target to build an object file
src/decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/decode.c.o
.PHONY : src/decode.c.o

src/decode.i: src/decode.c.i
.PHONY : src/decode.i

# target to preprocess a source file
src/decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/decode.c.i
.PHONY : src/decode.c.i

src/decode.s: src/decode.c.s
.PHONY : src/decode.s

# target to generate assembly for a file
src/decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/decode.c.s
.PHONY : src/decode.c.s

src/decompress.o: src/decompress.c.o
.PHONY : src/decompress.o

# target to build an object file
src/decompress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/decompress.c.o
.PHONY : src/decompress.c.o

src/decompress.i: src/decompress.c.i
.PHONY : src/decompress.i

# target to preprocess a source file
src/decompress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/decompress.c.i
.PHONY : src/decompress.c.i

src/decompress.s: src/decompress.c.s
.PHONY : src/decompress.s

# target to generate assembly for a file
src/decompress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/decompress.c.s
.PHONY : src/decompress.c.s

src/encode.o: src/encode.c.o
.PHONY : src/encode.o

# target to build an object file
src/encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/encode.c.o
.PHONY : src/encode.c.o

src/encode.i: src/encode.c.i
.PHONY : src/encode.i

# target to preprocess a source file
src/encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/encode.c.i
.PHONY : src/encode.c.i

src/encode.s: src/encode.c.s
.PHONY : src/encode.s

# target to generate assembly for a file
src/encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/encode.c.s
.PHONY : src/encode.c.s

src/extract.o: src/extract.c.o
.PHONY : src/extract.o

# target to build an object file
src/extract.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/extract.c.o
.PHONY : src/extract.c.o

src/extract.i: src/extract.c.i
.PHONY : src/extract.i

# target to preprocess a source file
src/extract.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/extract.c.i
.PHONY : src/extract.c.i

src/extract.s: src/extract.c.s
.PHONY : src/extract.s

# target to generate assembly for a file
src/extract.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/extract.c.s
.PHONY : src/extract.c.s

src/file.o: src/file.c.o
.PHONY : src/file.o

# target to build an object file
src/file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/file.c.o
.PHONY : src/file.c.o

src/file.i: src/file.c.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/file.c.i
.PHONY : src/file.c.i

src/file.s: src/file.c.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/file.c.s
.PHONY : src/file.c.s

src/mem.o: src/mem.c.o
.PHONY : src/mem.o

# target to build an object file
src/mem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/mem.c.o
.PHONY : src/mem.c.o

src/mem.i: src/mem.c.i
.PHONY : src/mem.i

# target to preprocess a source file
src/mem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/mem.c.i
.PHONY : src/mem.c.i

src/mem.s: src/mem.c.s
.PHONY : src/mem.s

# target to generate assembly for a file
src/mem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/mem.c.s
.PHONY : src/mem.c.s

src/mscompress.o: src/mscompress.c.o
.PHONY : src/mscompress.o

# target to build an object file
src/mscompress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/mscompress.c.o
.PHONY : src/mscompress.c.o

src/mscompress.i: src/mscompress.c.i
.PHONY : src/mscompress.i

# target to preprocess a source file
src/mscompress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/mscompress.c.i
.PHONY : src/mscompress.c.i

src/mscompress.s: src/mscompress.c.s
.PHONY : src/mscompress.s

# target to generate assembly for a file
src/mscompress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/mscompress.c.s
.PHONY : src/mscompress.c.s

src/preprocess.o: src/preprocess.c.o
.PHONY : src/preprocess.o

# target to build an object file
src/preprocess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/preprocess.c.o
.PHONY : src/preprocess.c.o

src/preprocess.i: src/preprocess.c.i
.PHONY : src/preprocess.i

# target to preprocess a source file
src/preprocess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/preprocess.c.i
.PHONY : src/preprocess.c.i

src/preprocess.s: src/preprocess.c.s
.PHONY : src/preprocess.s

# target to generate assembly for a file
src/preprocess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/preprocess.c.s
.PHONY : src/preprocess.c.s

src/queue.o: src/queue.c.o
.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i
.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s
.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/sys.o: src/sys.c.o
.PHONY : src/sys.o

# target to build an object file
src/sys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/sys.c.o
.PHONY : src/sys.c.o

src/sys.i: src/sys.c.i
.PHONY : src/sys.i

# target to preprocess a source file
src/sys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/sys.c.i
.PHONY : src/sys.c.i

src/sys.s: src/sys.c.s
.PHONY : src/sys.s

# target to generate assembly for a file
src/sys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/sys.c.s
.PHONY : src/sys.c.s

src/zl.o: src/zl.c.o
.PHONY : src/zl.o

# target to build an object file
src/zl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/zl.c.o
.PHONY : src/zl.c.o

src/zl.i: src/zl.c.i
.PHONY : src/zl.i

# target to preprocess a source file
src/zl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/zl.c.i
.PHONY : src/zl.c.i

src/zl.s: src/zl.c.s
.PHONY : src/zl.s

# target to generate assembly for a file
src/zl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mscompress.dir/build.make CMakeFiles/mscompress.dir/src/zl.c.s
.PHONY : src/zl.c.s

vendor/base64/lib/arch/avx/codec.o: vendor/base64/lib/arch/avx/codec.c.o
.PHONY : vendor/base64/lib/arch/avx/codec.o

# target to build an object file
vendor/base64/lib/arch/avx/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/avx/codec.c.o
.PHONY : vendor/base64/lib/arch/avx/codec.c.o

vendor/base64/lib/arch/avx/codec.i: vendor/base64/lib/arch/avx/codec.c.i
.PHONY : vendor/base64/lib/arch/avx/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/avx/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/avx/codec.c.i
.PHONY : vendor/base64/lib/arch/avx/codec.c.i

vendor/base64/lib/arch/avx/codec.s: vendor/base64/lib/arch/avx/codec.c.s
.PHONY : vendor/base64/lib/arch/avx/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/avx/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/avx/codec.c.s
.PHONY : vendor/base64/lib/arch/avx/codec.c.s

vendor/base64/lib/arch/avx2/codec.o: vendor/base64/lib/arch/avx2/codec.c.o
.PHONY : vendor/base64/lib/arch/avx2/codec.o

# target to build an object file
vendor/base64/lib/arch/avx2/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/avx2/codec.c.o
.PHONY : vendor/base64/lib/arch/avx2/codec.c.o

vendor/base64/lib/arch/avx2/codec.i: vendor/base64/lib/arch/avx2/codec.c.i
.PHONY : vendor/base64/lib/arch/avx2/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/avx2/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/avx2/codec.c.i
.PHONY : vendor/base64/lib/arch/avx2/codec.c.i

vendor/base64/lib/arch/avx2/codec.s: vendor/base64/lib/arch/avx2/codec.c.s
.PHONY : vendor/base64/lib/arch/avx2/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/avx2/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/avx2/codec.c.s
.PHONY : vendor/base64/lib/arch/avx2/codec.c.s

vendor/base64/lib/arch/generic/codec.o: vendor/base64/lib/arch/generic/codec.c.o
.PHONY : vendor/base64/lib/arch/generic/codec.o

# target to build an object file
vendor/base64/lib/arch/generic/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/generic/codec.c.o
.PHONY : vendor/base64/lib/arch/generic/codec.c.o

vendor/base64/lib/arch/generic/codec.i: vendor/base64/lib/arch/generic/codec.c.i
.PHONY : vendor/base64/lib/arch/generic/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/generic/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/generic/codec.c.i
.PHONY : vendor/base64/lib/arch/generic/codec.c.i

vendor/base64/lib/arch/generic/codec.s: vendor/base64/lib/arch/generic/codec.c.s
.PHONY : vendor/base64/lib/arch/generic/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/generic/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/generic/codec.c.s
.PHONY : vendor/base64/lib/arch/generic/codec.c.s

vendor/base64/lib/arch/neon32/codec.o: vendor/base64/lib/arch/neon32/codec.c.o
.PHONY : vendor/base64/lib/arch/neon32/codec.o

# target to build an object file
vendor/base64/lib/arch/neon32/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/neon32/codec.c.o
.PHONY : vendor/base64/lib/arch/neon32/codec.c.o

vendor/base64/lib/arch/neon32/codec.i: vendor/base64/lib/arch/neon32/codec.c.i
.PHONY : vendor/base64/lib/arch/neon32/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/neon32/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/neon32/codec.c.i
.PHONY : vendor/base64/lib/arch/neon32/codec.c.i

vendor/base64/lib/arch/neon32/codec.s: vendor/base64/lib/arch/neon32/codec.c.s
.PHONY : vendor/base64/lib/arch/neon32/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/neon32/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/neon32/codec.c.s
.PHONY : vendor/base64/lib/arch/neon32/codec.c.s

vendor/base64/lib/arch/neon64/codec.o: vendor/base64/lib/arch/neon64/codec.c.o
.PHONY : vendor/base64/lib/arch/neon64/codec.o

# target to build an object file
vendor/base64/lib/arch/neon64/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/neon64/codec.c.o
.PHONY : vendor/base64/lib/arch/neon64/codec.c.o

vendor/base64/lib/arch/neon64/codec.i: vendor/base64/lib/arch/neon64/codec.c.i
.PHONY : vendor/base64/lib/arch/neon64/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/neon64/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/neon64/codec.c.i
.PHONY : vendor/base64/lib/arch/neon64/codec.c.i

vendor/base64/lib/arch/neon64/codec.s: vendor/base64/lib/arch/neon64/codec.c.s
.PHONY : vendor/base64/lib/arch/neon64/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/neon64/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/neon64/codec.c.s
.PHONY : vendor/base64/lib/arch/neon64/codec.c.s

vendor/base64/lib/arch/sse41/codec.o: vendor/base64/lib/arch/sse41/codec.c.o
.PHONY : vendor/base64/lib/arch/sse41/codec.o

# target to build an object file
vendor/base64/lib/arch/sse41/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/sse41/codec.c.o
.PHONY : vendor/base64/lib/arch/sse41/codec.c.o

vendor/base64/lib/arch/sse41/codec.i: vendor/base64/lib/arch/sse41/codec.c.i
.PHONY : vendor/base64/lib/arch/sse41/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/sse41/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/sse41/codec.c.i
.PHONY : vendor/base64/lib/arch/sse41/codec.c.i

vendor/base64/lib/arch/sse41/codec.s: vendor/base64/lib/arch/sse41/codec.c.s
.PHONY : vendor/base64/lib/arch/sse41/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/sse41/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/sse41/codec.c.s
.PHONY : vendor/base64/lib/arch/sse41/codec.c.s

vendor/base64/lib/arch/sse42/codec.o: vendor/base64/lib/arch/sse42/codec.c.o
.PHONY : vendor/base64/lib/arch/sse42/codec.o

# target to build an object file
vendor/base64/lib/arch/sse42/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/sse42/codec.c.o
.PHONY : vendor/base64/lib/arch/sse42/codec.c.o

vendor/base64/lib/arch/sse42/codec.i: vendor/base64/lib/arch/sse42/codec.c.i
.PHONY : vendor/base64/lib/arch/sse42/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/sse42/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/sse42/codec.c.i
.PHONY : vendor/base64/lib/arch/sse42/codec.c.i

vendor/base64/lib/arch/sse42/codec.s: vendor/base64/lib/arch/sse42/codec.c.s
.PHONY : vendor/base64/lib/arch/sse42/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/sse42/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/sse42/codec.c.s
.PHONY : vendor/base64/lib/arch/sse42/codec.c.s

vendor/base64/lib/arch/ssse3/codec.o: vendor/base64/lib/arch/ssse3/codec.c.o
.PHONY : vendor/base64/lib/arch/ssse3/codec.o

# target to build an object file
vendor/base64/lib/arch/ssse3/codec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/ssse3/codec.c.o
.PHONY : vendor/base64/lib/arch/ssse3/codec.c.o

vendor/base64/lib/arch/ssse3/codec.i: vendor/base64/lib/arch/ssse3/codec.c.i
.PHONY : vendor/base64/lib/arch/ssse3/codec.i

# target to preprocess a source file
vendor/base64/lib/arch/ssse3/codec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/ssse3/codec.c.i
.PHONY : vendor/base64/lib/arch/ssse3/codec.c.i

vendor/base64/lib/arch/ssse3/codec.s: vendor/base64/lib/arch/ssse3/codec.c.s
.PHONY : vendor/base64/lib/arch/ssse3/codec.s

# target to generate assembly for a file
vendor/base64/lib/arch/ssse3/codec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/arch/ssse3/codec.c.s
.PHONY : vendor/base64/lib/arch/ssse3/codec.c.s

vendor/base64/lib/codec_choose.o: vendor/base64/lib/codec_choose.c.o
.PHONY : vendor/base64/lib/codec_choose.o

# target to build an object file
vendor/base64/lib/codec_choose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/codec_choose.c.o
.PHONY : vendor/base64/lib/codec_choose.c.o

vendor/base64/lib/codec_choose.i: vendor/base64/lib/codec_choose.c.i
.PHONY : vendor/base64/lib/codec_choose.i

# target to preprocess a source file
vendor/base64/lib/codec_choose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/codec_choose.c.i
.PHONY : vendor/base64/lib/codec_choose.c.i

vendor/base64/lib/codec_choose.s: vendor/base64/lib/codec_choose.c.s
.PHONY : vendor/base64/lib/codec_choose.s

# target to generate assembly for a file
vendor/base64/lib/codec_choose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/codec_choose.c.s
.PHONY : vendor/base64/lib/codec_choose.c.s

vendor/base64/lib/lib.o: vendor/base64/lib/lib.c.o
.PHONY : vendor/base64/lib/lib.o

# target to build an object file
vendor/base64/lib/lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/lib.c.o
.PHONY : vendor/base64/lib/lib.c.o

vendor/base64/lib/lib.i: vendor/base64/lib/lib.c.i
.PHONY : vendor/base64/lib/lib.i

# target to preprocess a source file
vendor/base64/lib/lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/lib.c.i
.PHONY : vendor/base64/lib/lib.c.i

vendor/base64/lib/lib.s: vendor/base64/lib/lib.c.s
.PHONY : vendor/base64/lib/lib.s

# target to generate assembly for a file
vendor/base64/lib/lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/lib.c.s
.PHONY : vendor/base64/lib/lib.c.s

vendor/base64/lib/tables/tables.o: vendor/base64/lib/tables/tables.c.o
.PHONY : vendor/base64/lib/tables/tables.o

# target to build an object file
vendor/base64/lib/tables/tables.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/tables/tables.c.o
.PHONY : vendor/base64/lib/tables/tables.c.o

vendor/base64/lib/tables/tables.i: vendor/base64/lib/tables/tables.c.i
.PHONY : vendor/base64/lib/tables/tables.i

# target to preprocess a source file
vendor/base64/lib/tables/tables.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/tables/tables.c.i
.PHONY : vendor/base64/lib/tables/tables.c.i

vendor/base64/lib/tables/tables.s: vendor/base64/lib/tables/tables.c.s
.PHONY : vendor/base64/lib/tables/tables.s

# target to generate assembly for a file
vendor/base64/lib/tables/tables.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/base64.dir/build.make CMakeFiles/base64.dir/vendor/base64/lib/tables/tables.c.s
.PHONY : vendor/base64/lib/tables/tables.c.s

vendor/yxml/yxml.o: vendor/yxml/yxml.c.o
.PHONY : vendor/yxml/yxml.o

# target to build an object file
vendor/yxml/yxml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yxml.dir/build.make CMakeFiles/yxml.dir/vendor/yxml/yxml.c.o
.PHONY : vendor/yxml/yxml.c.o

vendor/yxml/yxml.i: vendor/yxml/yxml.c.i
.PHONY : vendor/yxml/yxml.i

# target to preprocess a source file
vendor/yxml/yxml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yxml.dir/build.make CMakeFiles/yxml.dir/vendor/yxml/yxml.c.i
.PHONY : vendor/yxml/yxml.c.i

vendor/yxml/yxml.s: vendor/yxml/yxml.c.s
.PHONY : vendor/yxml/yxml.s

# target to generate assembly for a file
vendor/yxml/yxml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yxml.dir/build.make CMakeFiles/yxml.dir/vendor/yxml/yxml.c.s
.PHONY : vendor/yxml/yxml.c.s

vendor/zstd/lib/common/debug.o: vendor/zstd/lib/common/debug.c.o
.PHONY : vendor/zstd/lib/common/debug.o

# target to build an object file
vendor/zstd/lib/common/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/debug.c.o
.PHONY : vendor/zstd/lib/common/debug.c.o

vendor/zstd/lib/common/debug.i: vendor/zstd/lib/common/debug.c.i
.PHONY : vendor/zstd/lib/common/debug.i

# target to preprocess a source file
vendor/zstd/lib/common/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/debug.c.i
.PHONY : vendor/zstd/lib/common/debug.c.i

vendor/zstd/lib/common/debug.s: vendor/zstd/lib/common/debug.c.s
.PHONY : vendor/zstd/lib/common/debug.s

# target to generate assembly for a file
vendor/zstd/lib/common/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/debug.c.s
.PHONY : vendor/zstd/lib/common/debug.c.s

vendor/zstd/lib/common/entropy_common.o: vendor/zstd/lib/common/entropy_common.c.o
.PHONY : vendor/zstd/lib/common/entropy_common.o

# target to build an object file
vendor/zstd/lib/common/entropy_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/entropy_common.c.o
.PHONY : vendor/zstd/lib/common/entropy_common.c.o

vendor/zstd/lib/common/entropy_common.i: vendor/zstd/lib/common/entropy_common.c.i
.PHONY : vendor/zstd/lib/common/entropy_common.i

# target to preprocess a source file
vendor/zstd/lib/common/entropy_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/entropy_common.c.i
.PHONY : vendor/zstd/lib/common/entropy_common.c.i

vendor/zstd/lib/common/entropy_common.s: vendor/zstd/lib/common/entropy_common.c.s
.PHONY : vendor/zstd/lib/common/entropy_common.s

# target to generate assembly for a file
vendor/zstd/lib/common/entropy_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/entropy_common.c.s
.PHONY : vendor/zstd/lib/common/entropy_common.c.s

vendor/zstd/lib/common/error_private.o: vendor/zstd/lib/common/error_private.c.o
.PHONY : vendor/zstd/lib/common/error_private.o

# target to build an object file
vendor/zstd/lib/common/error_private.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/error_private.c.o
.PHONY : vendor/zstd/lib/common/error_private.c.o

vendor/zstd/lib/common/error_private.i: vendor/zstd/lib/common/error_private.c.i
.PHONY : vendor/zstd/lib/common/error_private.i

# target to preprocess a source file
vendor/zstd/lib/common/error_private.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/error_private.c.i
.PHONY : vendor/zstd/lib/common/error_private.c.i

vendor/zstd/lib/common/error_private.s: vendor/zstd/lib/common/error_private.c.s
.PHONY : vendor/zstd/lib/common/error_private.s

# target to generate assembly for a file
vendor/zstd/lib/common/error_private.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/error_private.c.s
.PHONY : vendor/zstd/lib/common/error_private.c.s

vendor/zstd/lib/common/fse_decompress.o: vendor/zstd/lib/common/fse_decompress.c.o
.PHONY : vendor/zstd/lib/common/fse_decompress.o

# target to build an object file
vendor/zstd/lib/common/fse_decompress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/fse_decompress.c.o
.PHONY : vendor/zstd/lib/common/fse_decompress.c.o

vendor/zstd/lib/common/fse_decompress.i: vendor/zstd/lib/common/fse_decompress.c.i
.PHONY : vendor/zstd/lib/common/fse_decompress.i

# target to preprocess a source file
vendor/zstd/lib/common/fse_decompress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/fse_decompress.c.i
.PHONY : vendor/zstd/lib/common/fse_decompress.c.i

vendor/zstd/lib/common/fse_decompress.s: vendor/zstd/lib/common/fse_decompress.c.s
.PHONY : vendor/zstd/lib/common/fse_decompress.s

# target to generate assembly for a file
vendor/zstd/lib/common/fse_decompress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/fse_decompress.c.s
.PHONY : vendor/zstd/lib/common/fse_decompress.c.s

vendor/zstd/lib/common/pool.o: vendor/zstd/lib/common/pool.c.o
.PHONY : vendor/zstd/lib/common/pool.o

# target to build an object file
vendor/zstd/lib/common/pool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/pool.c.o
.PHONY : vendor/zstd/lib/common/pool.c.o

vendor/zstd/lib/common/pool.i: vendor/zstd/lib/common/pool.c.i
.PHONY : vendor/zstd/lib/common/pool.i

# target to preprocess a source file
vendor/zstd/lib/common/pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/pool.c.i
.PHONY : vendor/zstd/lib/common/pool.c.i

vendor/zstd/lib/common/pool.s: vendor/zstd/lib/common/pool.c.s
.PHONY : vendor/zstd/lib/common/pool.s

# target to generate assembly for a file
vendor/zstd/lib/common/pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/pool.c.s
.PHONY : vendor/zstd/lib/common/pool.c.s

vendor/zstd/lib/common/threading.o: vendor/zstd/lib/common/threading.c.o
.PHONY : vendor/zstd/lib/common/threading.o

# target to build an object file
vendor/zstd/lib/common/threading.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/threading.c.o
.PHONY : vendor/zstd/lib/common/threading.c.o

vendor/zstd/lib/common/threading.i: vendor/zstd/lib/common/threading.c.i
.PHONY : vendor/zstd/lib/common/threading.i

# target to preprocess a source file
vendor/zstd/lib/common/threading.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/threading.c.i
.PHONY : vendor/zstd/lib/common/threading.c.i

vendor/zstd/lib/common/threading.s: vendor/zstd/lib/common/threading.c.s
.PHONY : vendor/zstd/lib/common/threading.s

# target to generate assembly for a file
vendor/zstd/lib/common/threading.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/threading.c.s
.PHONY : vendor/zstd/lib/common/threading.c.s

vendor/zstd/lib/common/xxhash.o: vendor/zstd/lib/common/xxhash.c.o
.PHONY : vendor/zstd/lib/common/xxhash.o

# target to build an object file
vendor/zstd/lib/common/xxhash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/xxhash.c.o
.PHONY : vendor/zstd/lib/common/xxhash.c.o

vendor/zstd/lib/common/xxhash.i: vendor/zstd/lib/common/xxhash.c.i
.PHONY : vendor/zstd/lib/common/xxhash.i

# target to preprocess a source file
vendor/zstd/lib/common/xxhash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/xxhash.c.i
.PHONY : vendor/zstd/lib/common/xxhash.c.i

vendor/zstd/lib/common/xxhash.s: vendor/zstd/lib/common/xxhash.c.s
.PHONY : vendor/zstd/lib/common/xxhash.s

# target to generate assembly for a file
vendor/zstd/lib/common/xxhash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/xxhash.c.s
.PHONY : vendor/zstd/lib/common/xxhash.c.s

vendor/zstd/lib/common/zstd_common.o: vendor/zstd/lib/common/zstd_common.c.o
.PHONY : vendor/zstd/lib/common/zstd_common.o

# target to build an object file
vendor/zstd/lib/common/zstd_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/zstd_common.c.o
.PHONY : vendor/zstd/lib/common/zstd_common.c.o

vendor/zstd/lib/common/zstd_common.i: vendor/zstd/lib/common/zstd_common.c.i
.PHONY : vendor/zstd/lib/common/zstd_common.i

# target to preprocess a source file
vendor/zstd/lib/common/zstd_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/zstd_common.c.i
.PHONY : vendor/zstd/lib/common/zstd_common.c.i

vendor/zstd/lib/common/zstd_common.s: vendor/zstd/lib/common/zstd_common.c.s
.PHONY : vendor/zstd/lib/common/zstd_common.s

# target to generate assembly for a file
vendor/zstd/lib/common/zstd_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/common/zstd_common.c.s
.PHONY : vendor/zstd/lib/common/zstd_common.c.s

vendor/zstd/lib/compress/fse_compress.o: vendor/zstd/lib/compress/fse_compress.c.o
.PHONY : vendor/zstd/lib/compress/fse_compress.o

# target to build an object file
vendor/zstd/lib/compress/fse_compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/fse_compress.c.o
.PHONY : vendor/zstd/lib/compress/fse_compress.c.o

vendor/zstd/lib/compress/fse_compress.i: vendor/zstd/lib/compress/fse_compress.c.i
.PHONY : vendor/zstd/lib/compress/fse_compress.i

# target to preprocess a source file
vendor/zstd/lib/compress/fse_compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/fse_compress.c.i
.PHONY : vendor/zstd/lib/compress/fse_compress.c.i

vendor/zstd/lib/compress/fse_compress.s: vendor/zstd/lib/compress/fse_compress.c.s
.PHONY : vendor/zstd/lib/compress/fse_compress.s

# target to generate assembly for a file
vendor/zstd/lib/compress/fse_compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/fse_compress.c.s
.PHONY : vendor/zstd/lib/compress/fse_compress.c.s

vendor/zstd/lib/compress/hist.o: vendor/zstd/lib/compress/hist.c.o
.PHONY : vendor/zstd/lib/compress/hist.o

# target to build an object file
vendor/zstd/lib/compress/hist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/hist.c.o
.PHONY : vendor/zstd/lib/compress/hist.c.o

vendor/zstd/lib/compress/hist.i: vendor/zstd/lib/compress/hist.c.i
.PHONY : vendor/zstd/lib/compress/hist.i

# target to preprocess a source file
vendor/zstd/lib/compress/hist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/hist.c.i
.PHONY : vendor/zstd/lib/compress/hist.c.i

vendor/zstd/lib/compress/hist.s: vendor/zstd/lib/compress/hist.c.s
.PHONY : vendor/zstd/lib/compress/hist.s

# target to generate assembly for a file
vendor/zstd/lib/compress/hist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/hist.c.s
.PHONY : vendor/zstd/lib/compress/hist.c.s

vendor/zstd/lib/compress/huf_compress.o: vendor/zstd/lib/compress/huf_compress.c.o
.PHONY : vendor/zstd/lib/compress/huf_compress.o

# target to build an object file
vendor/zstd/lib/compress/huf_compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/huf_compress.c.o
.PHONY : vendor/zstd/lib/compress/huf_compress.c.o

vendor/zstd/lib/compress/huf_compress.i: vendor/zstd/lib/compress/huf_compress.c.i
.PHONY : vendor/zstd/lib/compress/huf_compress.i

# target to preprocess a source file
vendor/zstd/lib/compress/huf_compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/huf_compress.c.i
.PHONY : vendor/zstd/lib/compress/huf_compress.c.i

vendor/zstd/lib/compress/huf_compress.s: vendor/zstd/lib/compress/huf_compress.c.s
.PHONY : vendor/zstd/lib/compress/huf_compress.s

# target to generate assembly for a file
vendor/zstd/lib/compress/huf_compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/huf_compress.c.s
.PHONY : vendor/zstd/lib/compress/huf_compress.c.s

vendor/zstd/lib/compress/zstd_compress.o: vendor/zstd/lib/compress/zstd_compress.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress.o

# target to build an object file
vendor/zstd/lib/compress/zstd_compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress.c.o

vendor/zstd/lib/compress/zstd_compress.i: vendor/zstd/lib/compress/zstd_compress.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress.c.i

vendor/zstd/lib/compress/zstd_compress.s: vendor/zstd/lib/compress/zstd_compress.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress.c.s

vendor/zstd/lib/compress/zstd_compress_literals.o: vendor/zstd/lib/compress/zstd_compress_literals.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress_literals.o

# target to build an object file
vendor/zstd/lib/compress/zstd_compress_literals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_literals.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress_literals.c.o

vendor/zstd/lib/compress/zstd_compress_literals.i: vendor/zstd/lib/compress/zstd_compress_literals.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress_literals.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_compress_literals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_literals.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress_literals.c.i

vendor/zstd/lib/compress/zstd_compress_literals.s: vendor/zstd/lib/compress/zstd_compress_literals.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress_literals.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_compress_literals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_literals.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress_literals.c.s

vendor/zstd/lib/compress/zstd_compress_sequences.o: vendor/zstd/lib/compress/zstd_compress_sequences.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress_sequences.o

# target to build an object file
vendor/zstd/lib/compress/zstd_compress_sequences.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_sequences.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress_sequences.c.o

vendor/zstd/lib/compress/zstd_compress_sequences.i: vendor/zstd/lib/compress/zstd_compress_sequences.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress_sequences.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_compress_sequences.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_sequences.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress_sequences.c.i

vendor/zstd/lib/compress/zstd_compress_sequences.s: vendor/zstd/lib/compress/zstd_compress_sequences.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress_sequences.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_compress_sequences.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_sequences.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress_sequences.c.s

vendor/zstd/lib/compress/zstd_compress_superblock.o: vendor/zstd/lib/compress/zstd_compress_superblock.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress_superblock.o

# target to build an object file
vendor/zstd/lib/compress/zstd_compress_superblock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_superblock.c.o
.PHONY : vendor/zstd/lib/compress/zstd_compress_superblock.c.o

vendor/zstd/lib/compress/zstd_compress_superblock.i: vendor/zstd/lib/compress/zstd_compress_superblock.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress_superblock.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_compress_superblock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_superblock.c.i
.PHONY : vendor/zstd/lib/compress/zstd_compress_superblock.c.i

vendor/zstd/lib/compress/zstd_compress_superblock.s: vendor/zstd/lib/compress/zstd_compress_superblock.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress_superblock.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_compress_superblock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_compress_superblock.c.s
.PHONY : vendor/zstd/lib/compress/zstd_compress_superblock.c.s

vendor/zstd/lib/compress/zstd_double_fast.o: vendor/zstd/lib/compress/zstd_double_fast.c.o
.PHONY : vendor/zstd/lib/compress/zstd_double_fast.o

# target to build an object file
vendor/zstd/lib/compress/zstd_double_fast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_double_fast.c.o
.PHONY : vendor/zstd/lib/compress/zstd_double_fast.c.o

vendor/zstd/lib/compress/zstd_double_fast.i: vendor/zstd/lib/compress/zstd_double_fast.c.i
.PHONY : vendor/zstd/lib/compress/zstd_double_fast.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_double_fast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_double_fast.c.i
.PHONY : vendor/zstd/lib/compress/zstd_double_fast.c.i

vendor/zstd/lib/compress/zstd_double_fast.s: vendor/zstd/lib/compress/zstd_double_fast.c.s
.PHONY : vendor/zstd/lib/compress/zstd_double_fast.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_double_fast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_double_fast.c.s
.PHONY : vendor/zstd/lib/compress/zstd_double_fast.c.s

vendor/zstd/lib/compress/zstd_fast.o: vendor/zstd/lib/compress/zstd_fast.c.o
.PHONY : vendor/zstd/lib/compress/zstd_fast.o

# target to build an object file
vendor/zstd/lib/compress/zstd_fast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_fast.c.o
.PHONY : vendor/zstd/lib/compress/zstd_fast.c.o

vendor/zstd/lib/compress/zstd_fast.i: vendor/zstd/lib/compress/zstd_fast.c.i
.PHONY : vendor/zstd/lib/compress/zstd_fast.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_fast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_fast.c.i
.PHONY : vendor/zstd/lib/compress/zstd_fast.c.i

vendor/zstd/lib/compress/zstd_fast.s: vendor/zstd/lib/compress/zstd_fast.c.s
.PHONY : vendor/zstd/lib/compress/zstd_fast.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_fast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_fast.c.s
.PHONY : vendor/zstd/lib/compress/zstd_fast.c.s

vendor/zstd/lib/compress/zstd_lazy.o: vendor/zstd/lib/compress/zstd_lazy.c.o
.PHONY : vendor/zstd/lib/compress/zstd_lazy.o

# target to build an object file
vendor/zstd/lib/compress/zstd_lazy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_lazy.c.o
.PHONY : vendor/zstd/lib/compress/zstd_lazy.c.o

vendor/zstd/lib/compress/zstd_lazy.i: vendor/zstd/lib/compress/zstd_lazy.c.i
.PHONY : vendor/zstd/lib/compress/zstd_lazy.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_lazy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_lazy.c.i
.PHONY : vendor/zstd/lib/compress/zstd_lazy.c.i

vendor/zstd/lib/compress/zstd_lazy.s: vendor/zstd/lib/compress/zstd_lazy.c.s
.PHONY : vendor/zstd/lib/compress/zstd_lazy.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_lazy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_lazy.c.s
.PHONY : vendor/zstd/lib/compress/zstd_lazy.c.s

vendor/zstd/lib/compress/zstd_ldm.o: vendor/zstd/lib/compress/zstd_ldm.c.o
.PHONY : vendor/zstd/lib/compress/zstd_ldm.o

# target to build an object file
vendor/zstd/lib/compress/zstd_ldm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_ldm.c.o
.PHONY : vendor/zstd/lib/compress/zstd_ldm.c.o

vendor/zstd/lib/compress/zstd_ldm.i: vendor/zstd/lib/compress/zstd_ldm.c.i
.PHONY : vendor/zstd/lib/compress/zstd_ldm.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_ldm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_ldm.c.i
.PHONY : vendor/zstd/lib/compress/zstd_ldm.c.i

vendor/zstd/lib/compress/zstd_ldm.s: vendor/zstd/lib/compress/zstd_ldm.c.s
.PHONY : vendor/zstd/lib/compress/zstd_ldm.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_ldm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_ldm.c.s
.PHONY : vendor/zstd/lib/compress/zstd_ldm.c.s

vendor/zstd/lib/compress/zstd_opt.o: vendor/zstd/lib/compress/zstd_opt.c.o
.PHONY : vendor/zstd/lib/compress/zstd_opt.o

# target to build an object file
vendor/zstd/lib/compress/zstd_opt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_opt.c.o
.PHONY : vendor/zstd/lib/compress/zstd_opt.c.o

vendor/zstd/lib/compress/zstd_opt.i: vendor/zstd/lib/compress/zstd_opt.c.i
.PHONY : vendor/zstd/lib/compress/zstd_opt.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstd_opt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_opt.c.i
.PHONY : vendor/zstd/lib/compress/zstd_opt.c.i

vendor/zstd/lib/compress/zstd_opt.s: vendor/zstd/lib/compress/zstd_opt.c.s
.PHONY : vendor/zstd/lib/compress/zstd_opt.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstd_opt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstd_opt.c.s
.PHONY : vendor/zstd/lib/compress/zstd_opt.c.s

vendor/zstd/lib/compress/zstdmt_compress.o: vendor/zstd/lib/compress/zstdmt_compress.c.o
.PHONY : vendor/zstd/lib/compress/zstdmt_compress.o

# target to build an object file
vendor/zstd/lib/compress/zstdmt_compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstdmt_compress.c.o
.PHONY : vendor/zstd/lib/compress/zstdmt_compress.c.o

vendor/zstd/lib/compress/zstdmt_compress.i: vendor/zstd/lib/compress/zstdmt_compress.c.i
.PHONY : vendor/zstd/lib/compress/zstdmt_compress.i

# target to preprocess a source file
vendor/zstd/lib/compress/zstdmt_compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstdmt_compress.c.i
.PHONY : vendor/zstd/lib/compress/zstdmt_compress.c.i

vendor/zstd/lib/compress/zstdmt_compress.s: vendor/zstd/lib/compress/zstdmt_compress.c.s
.PHONY : vendor/zstd/lib/compress/zstdmt_compress.s

# target to generate assembly for a file
vendor/zstd/lib/compress/zstdmt_compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/compress/zstdmt_compress.c.s
.PHONY : vendor/zstd/lib/compress/zstdmt_compress.c.s

vendor/zstd/lib/decompress/huf_decompress.o: vendor/zstd/lib/decompress/huf_decompress.c.o
.PHONY : vendor/zstd/lib/decompress/huf_decompress.o

# target to build an object file
vendor/zstd/lib/decompress/huf_decompress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/huf_decompress.c.o
.PHONY : vendor/zstd/lib/decompress/huf_decompress.c.o

vendor/zstd/lib/decompress/huf_decompress.i: vendor/zstd/lib/decompress/huf_decompress.c.i
.PHONY : vendor/zstd/lib/decompress/huf_decompress.i

# target to preprocess a source file
vendor/zstd/lib/decompress/huf_decompress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/huf_decompress.c.i
.PHONY : vendor/zstd/lib/decompress/huf_decompress.c.i

vendor/zstd/lib/decompress/huf_decompress.s: vendor/zstd/lib/decompress/huf_decompress.c.s
.PHONY : vendor/zstd/lib/decompress/huf_decompress.s

# target to generate assembly for a file
vendor/zstd/lib/decompress/huf_decompress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/huf_decompress.c.s
.PHONY : vendor/zstd/lib/decompress/huf_decompress.c.s

vendor/zstd/lib/decompress/huf_decompress_amd64.o: vendor/zstd/lib/decompress/huf_decompress_amd64.S.o
.PHONY : vendor/zstd/lib/decompress/huf_decompress_amd64.o

# target to build an object file
vendor/zstd/lib/decompress/huf_decompress_amd64.S.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/huf_decompress_amd64.S.o
.PHONY : vendor/zstd/lib/decompress/huf_decompress_amd64.S.o

vendor/zstd/lib/decompress/zstd_ddict.o: vendor/zstd/lib/decompress/zstd_ddict.c.o
.PHONY : vendor/zstd/lib/decompress/zstd_ddict.o

# target to build an object file
vendor/zstd/lib/decompress/zstd_ddict.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_ddict.c.o
.PHONY : vendor/zstd/lib/decompress/zstd_ddict.c.o

vendor/zstd/lib/decompress/zstd_ddict.i: vendor/zstd/lib/decompress/zstd_ddict.c.i
.PHONY : vendor/zstd/lib/decompress/zstd_ddict.i

# target to preprocess a source file
vendor/zstd/lib/decompress/zstd_ddict.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_ddict.c.i
.PHONY : vendor/zstd/lib/decompress/zstd_ddict.c.i

vendor/zstd/lib/decompress/zstd_ddict.s: vendor/zstd/lib/decompress/zstd_ddict.c.s
.PHONY : vendor/zstd/lib/decompress/zstd_ddict.s

# target to generate assembly for a file
vendor/zstd/lib/decompress/zstd_ddict.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_ddict.c.s
.PHONY : vendor/zstd/lib/decompress/zstd_ddict.c.s

vendor/zstd/lib/decompress/zstd_decompress.o: vendor/zstd/lib/decompress/zstd_decompress.c.o
.PHONY : vendor/zstd/lib/decompress/zstd_decompress.o

# target to build an object file
vendor/zstd/lib/decompress/zstd_decompress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_decompress.c.o
.PHONY : vendor/zstd/lib/decompress/zstd_decompress.c.o

vendor/zstd/lib/decompress/zstd_decompress.i: vendor/zstd/lib/decompress/zstd_decompress.c.i
.PHONY : vendor/zstd/lib/decompress/zstd_decompress.i

# target to preprocess a source file
vendor/zstd/lib/decompress/zstd_decompress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_decompress.c.i
.PHONY : vendor/zstd/lib/decompress/zstd_decompress.c.i

vendor/zstd/lib/decompress/zstd_decompress.s: vendor/zstd/lib/decompress/zstd_decompress.c.s
.PHONY : vendor/zstd/lib/decompress/zstd_decompress.s

# target to generate assembly for a file
vendor/zstd/lib/decompress/zstd_decompress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_decompress.c.s
.PHONY : vendor/zstd/lib/decompress/zstd_decompress.c.s

vendor/zstd/lib/decompress/zstd_decompress_block.o: vendor/zstd/lib/decompress/zstd_decompress_block.c.o
.PHONY : vendor/zstd/lib/decompress/zstd_decompress_block.o

# target to build an object file
vendor/zstd/lib/decompress/zstd_decompress_block.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_decompress_block.c.o
.PHONY : vendor/zstd/lib/decompress/zstd_decompress_block.c.o

vendor/zstd/lib/decompress/zstd_decompress_block.i: vendor/zstd/lib/decompress/zstd_decompress_block.c.i
.PHONY : vendor/zstd/lib/decompress/zstd_decompress_block.i

# target to preprocess a source file
vendor/zstd/lib/decompress/zstd_decompress_block.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_decompress_block.c.i
.PHONY : vendor/zstd/lib/decompress/zstd_decompress_block.c.i

vendor/zstd/lib/decompress/zstd_decompress_block.s: vendor/zstd/lib/decompress/zstd_decompress_block.c.s
.PHONY : vendor/zstd/lib/decompress/zstd_decompress_block.s

# target to generate assembly for a file
vendor/zstd/lib/decompress/zstd_decompress_block.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zstd.dir/build.make CMakeFiles/zstd.dir/vendor/zstd/lib/decompress/zstd_decompress_block.c.s
.PHONY : vendor/zstd/lib/decompress/zstd_decompress_block.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zlib_build"
	@echo "... base64"
	@echo "... mscompress"
	@echo "... yxml"
	@echo "... zstd"
	@echo "... src/algo.o"
	@echo "... src/algo.i"
	@echo "... src/algo.s"
	@echo "... src/compress.o"
	@echo "... src/compress.i"
	@echo "... src/compress.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/decode.o"
	@echo "... src/decode.i"
	@echo "... src/decode.s"
	@echo "... src/decompress.o"
	@echo "... src/decompress.i"
	@echo "... src/decompress.s"
	@echo "... src/encode.o"
	@echo "... src/encode.i"
	@echo "... src/encode.s"
	@echo "... src/extract.o"
	@echo "... src/extract.i"
	@echo "... src/extract.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/mem.o"
	@echo "... src/mem.i"
	@echo "... src/mem.s"
	@echo "... src/mscompress.o"
	@echo "... src/mscompress.i"
	@echo "... src/mscompress.s"
	@echo "... src/preprocess.o"
	@echo "... src/preprocess.i"
	@echo "... src/preprocess.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/sys.o"
	@echo "... src/sys.i"
	@echo "... src/sys.s"
	@echo "... src/zl.o"
	@echo "... src/zl.i"
	@echo "... src/zl.s"
	@echo "... vendor/base64/lib/arch/avx/codec.o"
	@echo "... vendor/base64/lib/arch/avx/codec.i"
	@echo "... vendor/base64/lib/arch/avx/codec.s"
	@echo "... vendor/base64/lib/arch/avx2/codec.o"
	@echo "... vendor/base64/lib/arch/avx2/codec.i"
	@echo "... vendor/base64/lib/arch/avx2/codec.s"
	@echo "... vendor/base64/lib/arch/generic/codec.o"
	@echo "... vendor/base64/lib/arch/generic/codec.i"
	@echo "... vendor/base64/lib/arch/generic/codec.s"
	@echo "... vendor/base64/lib/arch/neon32/codec.o"
	@echo "... vendor/base64/lib/arch/neon32/codec.i"
	@echo "... vendor/base64/lib/arch/neon32/codec.s"
	@echo "... vendor/base64/lib/arch/neon64/codec.o"
	@echo "... vendor/base64/lib/arch/neon64/codec.i"
	@echo "... vendor/base64/lib/arch/neon64/codec.s"
	@echo "... vendor/base64/lib/arch/sse41/codec.o"
	@echo "... vendor/base64/lib/arch/sse41/codec.i"
	@echo "... vendor/base64/lib/arch/sse41/codec.s"
	@echo "... vendor/base64/lib/arch/sse42/codec.o"
	@echo "... vendor/base64/lib/arch/sse42/codec.i"
	@echo "... vendor/base64/lib/arch/sse42/codec.s"
	@echo "... vendor/base64/lib/arch/ssse3/codec.o"
	@echo "... vendor/base64/lib/arch/ssse3/codec.i"
	@echo "... vendor/base64/lib/arch/ssse3/codec.s"
	@echo "... vendor/base64/lib/codec_choose.o"
	@echo "... vendor/base64/lib/codec_choose.i"
	@echo "... vendor/base64/lib/codec_choose.s"
	@echo "... vendor/base64/lib/lib.o"
	@echo "... vendor/base64/lib/lib.i"
	@echo "... vendor/base64/lib/lib.s"
	@echo "... vendor/base64/lib/tables/tables.o"
	@echo "... vendor/base64/lib/tables/tables.i"
	@echo "... vendor/base64/lib/tables/tables.s"
	@echo "... vendor/yxml/yxml.o"
	@echo "... vendor/yxml/yxml.i"
	@echo "... vendor/yxml/yxml.s"
	@echo "... vendor/zstd/lib/common/debug.o"
	@echo "... vendor/zstd/lib/common/debug.i"
	@echo "... vendor/zstd/lib/common/debug.s"
	@echo "... vendor/zstd/lib/common/entropy_common.o"
	@echo "... vendor/zstd/lib/common/entropy_common.i"
	@echo "... vendor/zstd/lib/common/entropy_common.s"
	@echo "... vendor/zstd/lib/common/error_private.o"
	@echo "... vendor/zstd/lib/common/error_private.i"
	@echo "... vendor/zstd/lib/common/error_private.s"
	@echo "... vendor/zstd/lib/common/fse_decompress.o"
	@echo "... vendor/zstd/lib/common/fse_decompress.i"
	@echo "... vendor/zstd/lib/common/fse_decompress.s"
	@echo "... vendor/zstd/lib/common/pool.o"
	@echo "... vendor/zstd/lib/common/pool.i"
	@echo "... vendor/zstd/lib/common/pool.s"
	@echo "... vendor/zstd/lib/common/threading.o"
	@echo "... vendor/zstd/lib/common/threading.i"
	@echo "... vendor/zstd/lib/common/threading.s"
	@echo "... vendor/zstd/lib/common/xxhash.o"
	@echo "... vendor/zstd/lib/common/xxhash.i"
	@echo "... vendor/zstd/lib/common/xxhash.s"
	@echo "... vendor/zstd/lib/common/zstd_common.o"
	@echo "... vendor/zstd/lib/common/zstd_common.i"
	@echo "... vendor/zstd/lib/common/zstd_common.s"
	@echo "... vendor/zstd/lib/compress/fse_compress.o"
	@echo "... vendor/zstd/lib/compress/fse_compress.i"
	@echo "... vendor/zstd/lib/compress/fse_compress.s"
	@echo "... vendor/zstd/lib/compress/hist.o"
	@echo "... vendor/zstd/lib/compress/hist.i"
	@echo "... vendor/zstd/lib/compress/hist.s"
	@echo "... vendor/zstd/lib/compress/huf_compress.o"
	@echo "... vendor/zstd/lib/compress/huf_compress.i"
	@echo "... vendor/zstd/lib/compress/huf_compress.s"
	@echo "... vendor/zstd/lib/compress/zstd_compress.o"
	@echo "... vendor/zstd/lib/compress/zstd_compress.i"
	@echo "... vendor/zstd/lib/compress/zstd_compress.s"
	@echo "... vendor/zstd/lib/compress/zstd_compress_literals.o"
	@echo "... vendor/zstd/lib/compress/zstd_compress_literals.i"
	@echo "... vendor/zstd/lib/compress/zstd_compress_literals.s"
	@echo "... vendor/zstd/lib/compress/zstd_compress_sequences.o"
	@echo "... vendor/zstd/lib/compress/zstd_compress_sequences.i"
	@echo "... vendor/zstd/lib/compress/zstd_compress_sequences.s"
	@echo "... vendor/zstd/lib/compress/zstd_compress_superblock.o"
	@echo "... vendor/zstd/lib/compress/zstd_compress_superblock.i"
	@echo "... vendor/zstd/lib/compress/zstd_compress_superblock.s"
	@echo "... vendor/zstd/lib/compress/zstd_double_fast.o"
	@echo "... vendor/zstd/lib/compress/zstd_double_fast.i"
	@echo "... vendor/zstd/lib/compress/zstd_double_fast.s"
	@echo "... vendor/zstd/lib/compress/zstd_fast.o"
	@echo "... vendor/zstd/lib/compress/zstd_fast.i"
	@echo "... vendor/zstd/lib/compress/zstd_fast.s"
	@echo "... vendor/zstd/lib/compress/zstd_lazy.o"
	@echo "... vendor/zstd/lib/compress/zstd_lazy.i"
	@echo "... vendor/zstd/lib/compress/zstd_lazy.s"
	@echo "... vendor/zstd/lib/compress/zstd_ldm.o"
	@echo "... vendor/zstd/lib/compress/zstd_ldm.i"
	@echo "... vendor/zstd/lib/compress/zstd_ldm.s"
	@echo "... vendor/zstd/lib/compress/zstd_opt.o"
	@echo "... vendor/zstd/lib/compress/zstd_opt.i"
	@echo "... vendor/zstd/lib/compress/zstd_opt.s"
	@echo "... vendor/zstd/lib/compress/zstdmt_compress.o"
	@echo "... vendor/zstd/lib/compress/zstdmt_compress.i"
	@echo "... vendor/zstd/lib/compress/zstdmt_compress.s"
	@echo "... vendor/zstd/lib/decompress/huf_decompress.o"
	@echo "... vendor/zstd/lib/decompress/huf_decompress.i"
	@echo "... vendor/zstd/lib/decompress/huf_decompress.s"
	@echo "... vendor/zstd/lib/decompress/huf_decompress_amd64.o"
	@echo "... vendor/zstd/lib/decompress/zstd_ddict.o"
	@echo "... vendor/zstd/lib/decompress/zstd_ddict.i"
	@echo "... vendor/zstd/lib/decompress/zstd_ddict.s"
	@echo "... vendor/zstd/lib/decompress/zstd_decompress.o"
	@echo "... vendor/zstd/lib/decompress/zstd_decompress.i"
	@echo "... vendor/zstd/lib/decompress/zstd_decompress.s"
	@echo "... vendor/zstd/lib/decompress/zstd_decompress_block.o"
	@echo "... vendor/zstd/lib/decompress/zstd_decompress_block.i"
	@echo "... vendor/zstd/lib/decompress/zstd_decompress_block.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

